name: microtlv unit-tests
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Create Build Environment
      run: cmake -B${{runner.workspace}}/build .

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make test
